<?php
$page = "expunere-de-motive";

require 'include/header.php';
?>
<div class="jumbotron jumbotron-primary">
  <div class="container">
    <div class="row">
      <div class="col-md-6 banner">
        <div>
            <h1>Fără penali în funcții publice!</h1>
        </div>
        <h2>Inițiativa cetățenească de modificare a Constituției</h2>
    </div>
    </div>
  </div>
</div>
<div class="container expunere-de-motive">
<div class="col-md-8 main-content">
    <h1>Inițiativa</h1>
    <h4>Ajută la strângerea semnăturilor. Fiecare semnătură contează. <a href="#formular">Înscrie-te aici <span class="glyphicon glyphicon-menu-right"><span></a></h4>
<img src="build/img/expunere-de-motive.png" alt="">
<h2>Expunere de motive</h2>
<h5>Lege de revizuire a Constituției României</h5>
<p>Importanța deosebit de mare a relațiilor sociale care privesc alegerea prin vot a autorităților locale, deputaților, senatorilor, Președintelui României și europarlamentarilor, precum și incidența lor în procesul de instaurare, menținere și exercitare a puterii de stat, reprezintă principalele motive pentru care acestea sunt reglementate atât prin Constituție, legea fundamentală a statului român, cât și prin legile electorale, în număr de patru. Dintre toate categoriile de norme juridice, trăsătura esențială a normelor electorale este aceea că indică în modul cel mai direct și mai eficient caracterul democratic sau, dimpotrivă, nedemocratic, al unui sistem constituțional.</p>
<p>Într-o strânsă conexiune cu normele juridice electorale se află drepturile electorale, considerate a fi drepturi cetățenești fundamentale prin excelență și totodată drepturi cu caracter exclusiv politic, care nu pot fi exercitate decât de cetățeni și numai pentru participarea acestora la guvernare, în virtutea legăturilor pe care le au cu destinele societății în cadrul căreia le este recunoscut un atare statut. Din multitudinea drepturilor electorale recunoscute în dreptul românesc, majoritatea sunt reglementate prin legile organice, numai cele mai importante două fiind consacrate la nivel constituțional, respectiv dreptul de vot și dreptul de a fi ales.</p>
<p> În ceea ce privește dreptul de a fi ales, la modul general acesta desemnează aptitudinea unei persoane de a fi votată pentru a face parte din organele reprezentative ale statului și a îndeplini astfel o demnitate publică sau o funcție electivă. Conform art. 37 din Constituție, dreptul de a fi ales aparține în exclusivitate cetățenilor români care au drept de vot și domiciliul în țară, cu condiția să nu facă parte din categoriile de funcționari publici nominalizate la art. 40 alin. (3) din Constituție și în legile organice, cărora le este interzisă asocierea în partide politice.</p>
<p>Suplimentar față de aceste condiții sunt prevăzute și limite minime de vârstă pentru a candida, care diferă în funcție de tipul demnității pentru care se depune candidatura, astfel că pentru a putea fi ales în Camera Deputaților vârsta minimă este de 23 de ani, pentru a putea fi ales în Senat vârsta minimă este de 33 de ani, iar pentru a putea fi ales Președinte al României vârsta minimă este de 35 de ani, în toate situațiile fiind necesar ca vârsta să fie împlinită până cel târziu în ziua alegerilor, inclusiv.</p>
<p>Prima condiție, deținerea cetățeniei române, exclude străinii și apatrizii, despre care se consideră că nu au o legătură permanentă și stabilă cu statul și nu fac parte din comunitatea socială care stă la baza uniunii politice statale. Spre deosebire însă de versiunea inițială a Constituției, care impunea condiția deținerii numai a cetățeniei române, versiunea actuală rezultată în urma revizuirii din anul 2003 recunoaște dreptul de a fi ales inclusiv cetățenilor români cu dublă sau multiplă cetățenie.</p>
<p>A doua condiție, domicilierea pe teritoriul țării, este prevăzută de majoritatea constituțiilor lumii și reprezintă o garanție suplimentară a atașamentului persoanei față de țara la guvernarea căreia participă ca demnitar sau funcționar public. Nu în ultimul rând, îndeplinirea acestei condiții este esențială pentru asigurarea exercitării efective și în condiții de eficiență a oricărei funcții sau demnități publice.</p>
<p>A treia condiție, deținerea dreptului de vot, rezidă în strânsa corelație dintre cele două drepturi electorale fundamentale și în raportul de subsidiaritate care face de neconceput eventuala posibilitate ca cetățenii cărora le-a fost ridicat dreptul elementar de a vota să păstreze în continuare dreptul de a-și depune candidatura pentru a fi aleși în organele reprezentative ale statului.</p>
<p>A patra condiție, deținerea dreptului de asociere în partide politice, instituie o ineligibilitate a judecătorilor Curții Constituționale, avocaților poporului, magistraților, membrilor activi ai armatei, polițiștilor și altor categorii de funcționari publici stabilite prin lege organică, limitată însă la perioada în care cetățenii îndeplinesc funcțiile respective, în scopul evitării oricăror conflicte de interese.</p>
<p>A cincea și ultima condiție, împlinirea unei anumite vârste, se justifică prin importanța obligațiilor pe care și le asumă o persoană în fiecare astfel de funcție sau demnitate publică, prin responsabilitatea care revine celor desemnați să guverneze, prin maturitatea de care trebuie să dea dovadă în gestionarea problemelor statului și prin credibilitatea și experiența pe care candidații trebuie să le arate alegătorilor pentru ca aceștia să investească încredere și speranțe în viitorii lor reprezentanți.</p>
<p>Spre deosebire de persoanele care exercită funcțiile sau demnitățile publice anterior menționate și sunt alese prin votul egal, direct, secret şi liber exprimat al cetățenilor, Primul Ministru este propus de Președintele României și trebuie confirmat de Parlament, care se întrunește în ședință comună a Camerei Deputaților și Senatului pentru a decide dacă acordă sau nu încrederea Premierului și persoanelor pe care acesta le nominalizează pentru a alcătui Guvernul, în calitate de miniștri ai cabinetului său.</p>
<p>În legătură cu condițiile necesare pentru a ocupa funcția de membru al Guvernului, art. 105 din Constituție instituie incompatibilitatea cu exercitarea unei funcţii de reprezentare profesională salarizate în cadrul organizaţiilor cu scop comercial, precum și cu exercitarea oricărei funcții publice de autoritate în afara celei de deputat sau de senator, permițând însă în mod expres stabilirea altor incompatibilități prin lege organică.</p>
<p>Astfel, potrivit art. 2 din Legea nr. 90/2001 privind organizarea și funcționarea Guvernului României și a ministerelor, <em>"Pot fi membri ai Guvernului persoanele care au cetăţenia română şi domiciliul în ţară, se bucură de exerciţiul drepturilor electorale, nu au suferit condamnări penale şi nu se găsesc în unul dintre cazurile de incompatibilitate prevăzute în cartea I titlul IV din Legea nr. 161/2003 privind unele măsuri pentru asigurarea transparenţei în exercitarea demnităţilor publice, a funcţiilor publice şi în mediul de afaceri, prevenirea şi sancţionarea corupţiei, cu modificările şi completările ulterioare."</em></p>
<p>Coroborând art. 37 și art. 105 din Constituție cu art. 2 din Legea nr. 90/2001, se poate observa că îndeplinirea cumulativă a primelor trei condiții, respectiv cetățenia română, domiciliul în țară și dreptul de vot, este necesară atât pentru a fi votat în organele reprezentative ale statului, cât și pentru a fi propus și confirmat în funcția de membru al Guvernului, în timp ce condiția deținerii dreptului de asociere în partide politice rămâne valabilă doar în prima situație, deoarece în cea de-a doua restricția omoloagă este chiar mai severă, existând incompatibilitate cu orice funcție publică de autoritate, precum și cu funcțiile de reprezentare profesională salarizate din cadrul organizaţiilor cu scop comercial.</p>
<p>Cât despre necesitatea împlinirii unei anumite vârste, aceasta este lăsată la libera apreciere a Președintelui României, atunci când desemnează candidatul pentru funcția de Prim Ministru, a persoanei astfel propuse, atunci când alcătuiește lista viitorilor miniștri, precum și a membrilor Parlamentului, atunci când votează asupra învestiturii noului Guvern.</p>
<p>Pe de altă parte, legea organică prevede că pot fi membri ai Guvernului numai persoanele care nu au suferit condamnări penale, condiție care nu se regăsește în Constituție și nici în legile electorale, ceea ce l-a determinat pe Avocatul Poporului să sesizeze Curtea Constituțională cu o excepție de neconstituționalitate a art. 2 din Legea nr. 90/2001, prin care a criticat, în esență, lipsa de coerență legislativă în stabilirea unor criterii de integritate clare, obiective și general valabile pentru ocuparea funcțiilor aparținând celor trei puteri organizate în cadrul democrației constituționale.</p>
<p>În expunerea de motive a excepției au fost trecute în revistă situațiile parlamentarilor, magistraților și Președintelui României, care au fost comparate cu situația membrilor Guvernului, pentru evidențierea caracterului eterogen al condițiilor care trebuie întrunite pentru dobândirea calităților respective. Fără a contesta faptul că o persoană care urmează să ocupe o funcție ce implică exercițiul autorității de stat trebuie să îndeplinească anumite cerințe de integritate, legalitate și corectitudine, menite să consolideze încrederea cetățenilor în autoritățile statului, Avocatul Poporului a explicat că legislația care guvernează condițiile de accedere la o funcție sau demnitate publică trebuie să fie una coerentă, predictibilă și unitară, aplicabilă tuturor reprezentanților puterilor legislativă, executivă și judecătorească.</p>
<p>Curtea Constituțională a respins excepția prin Decizia nr. 304/2017, însă nu pentru motive de fond, ca neîntemeiată, ci pentru motive de formă, ca inadmisibilă, reținând printre altele faptul că <em>"examinarea constituționalității unui text de lege are în vedere compatibilitatea acestuia cu dispozițiile constituționale pretins încălcate, iar nu compararea prevederilor mai multor legi între ele și raportarea concluziei ce ar rezulta din această comparație la dispoziții ori principii ale Constituției"</em>. Din acest motiv, instanța de contencios constituțional a concluzionat că <em>"nu ține nici de rolul și nici de competența Curții Constituționale asigurarea coerenței legislative invocate de Avocatul Poporului, revenind astfel Parlamentului și Consiliului Legislativ obligația de a elimina o eventuală lipsă de coerență și de a unifica legislația în materia antereferită"</em>.</p>
<p>Prin prezenta inițiativă, ne propunem să remediem problemele semnalate de Avocatul Poporului prin consacrarea la nivel constituțional a unei condiții de integritate unitare, similară celei privind membrii Guvernului, ce ar urma să se aplice persoanelor care candidează pentru a fi alese în organele administrației publice locale, în Camera Deputaților, în Senat și în funcția de Președinte al României.</p>
<p>Considerăm că este imperios necesar ca legislația care guvernează condițiile de accedere la o funcție sau demnitate publică să fie coerentă, predictibilă și unitară, aplicabilă tuturor reprezentanților puterilor statului, astfel încât persoanele care urmează să ocupe o funcție ce implică exercițiul autorității de stat să îndeplinească anumite cerințe de integritate, legalitate și corectitudine, menite să consolideze încrederea cetățenilor în autoritățile publice și să preîntâmpine derapajele de la principiile democrației prin drept.</p>
<p>În elaborarea acestui proiect de lege, s-a avut permanent în vedere faptul că dreptul de a fi ales trebuie să fie, conform art. 20 din Constituție, interpretat și aplicat în concordanță cu Declarația Universală a Drepturilor Omului, cu pactele și cu celelalte tratate internaționale la care România este parte, dintre care cităm următoarele:</p>
<ul>
<li>Declarația Universală a Drepturilor Omului – Art. 21: <em>"(1) Orice persoană are dreptul de a lua parte la conducerea treburilor publice ale țării sale, fie direct, fie prin reprezentanți liber aleși. (2) Orice persoană are dreptul de acces egal la funcțiile publice din țara sa. (3) Voința poporului trebuie să constituie baza puterii de stat; această voință trebuie să fie exprimată prin alegeri nefalsificate, care să aibă loc în mod periodic prin sufragiu universal, egal și exprimat prin vot secret sau urmând o procedură echivalentă care să asigure libertatea votului."</em></li>
<li>Pactul internaţional cu privire la drepturile civile și politice – Art. 25: <em>"Orice cetățean are dreptul și posibilitatea, fără niciuna din discriminările la care se referă art. 2 și fără restricții nerezonabile: a) de a lua parte la conducerea treburilor publice, fie direct, fie prin intermediul unor reprezentanți liber aleși; b) de a alege și de a fi ales în cadrul unor alegeri periodice, oneste, cu sufragiu universal și egal și cu scrutin secret, asigurând libera exprimare a voinței alegătorilor; c) de a avea acces, în condițiile generale de egalitate, la funcțiile publice din țara sa."</em></li>
<li>Convenția Europeană a Drepturilor Omului - Primul Protocol Adițional – Art. 3: <em>"Înaltele Părţi Contractante se angajează să organizeze, la intervale rezonabile, alegeri libere cu vot secret, în condiţii care să asigure libera exprimare a opiniei poporului cu privire la alegerea corpului legislativ."</em></li>
</ul>
<p>Totodată, s-a ținut cont și de jurisprudența Curții Europene a Drepturilor Omului („CEDO") în domeniul drepturilor electorale, care a reliefat existența unei distincții clare între dreptul de a alege și dreptul de a fi ales, înclinând în favoarea conferirii unei protecții juridice superioare celui dintâi în raport cu cel de-al doilea, ce poate fi supus unor restricții semnificativ mai severe.</p>
<p>Astfel, referindu-se la dreptul de a alege, CEDO consideră că <em>"orice îndepărtare de la principiul votului universal riscă să submineze legitimitatea democratică a legislaturii astfel alese și implicit a legilor pe care aceasta le sancționează"</em>.  În legătură cu dreptul de a fi ales, CEDO apreciază că <em>"Ineligibilitatea trebuie în primul rând să fie reglementată prin norme de drept clare. Trebuie să urmărească un scop legitim."</em>, acceptând însă faptul că marja de apreciere a statelor membre este largă și că <em>"pot fi impuse condiții de eligibilitate mai stricte pentru a candida în alegerile parlamentare, comparativ cu eligibilitatea de a vota"</em>.</p>
<p>Așadar, jurisprudența asupra dreptului de a alege nu este aplicabilă în mod automat, mutatis mutandis, problemei ineligibilității, în special atunci când se implementează testul proporționalității restricțiilor. Cu toate acestea, se consideră că o regulă conform căreia orice persoană condamnată penal și-ar pierde automat dreptul de a fi aleasă ar contraveni Convenției Europene a Drepturilor Omului. Potrivit CEDO, <em>"statele contractante pot decide ori să permită instanțelor judecătorești să determine proporționalitatea unei măsuri de restrângere a drepturilor electorale ale persoanelor condamnate penal, ori să integreze prevederi în legile lor care definesc circumstanțele în care o asemenea măsură trebuie aplicată. În acest din urmă caz, va rămâne în seama legislaturii însăși să aprecieze interesele concurente pentru a evita orice restricție generală, automată și discriminatorie"</em>.</p>
<p>Conform Codului Bunelor Practici în Materie Electorală, elaborat de Comisia Europeană pentru Democrație prin Drept ("Comisia de la Veneția") din cadrul Consiliului Europei, persoanele pot fi private de drepturile electorale numai dacă sunt întrunite în mod cumulativ următoarele condiții: (i) măsura să fie reglementată prin lege; (ii) principiul proporționalității să fie respectat, condițiile pentru ridicarea dreptului de a candida putând fi mai puțin stricte decât cele pentru ridicarea dreptului de vot; (iii) măsura să fie motivată de o incapacitate mentală sau de o condamnare penală pentru o infracțiune gravă; (iv) retragerea drepturilor politice sau constatarea incapacității mentale să fie impusă prin hotărâre judecătorească.</p>
<p>Cu toate acestea, din perspectiva jurisprudenței CEDO, condiția existenței unei hotărâri judecătorești pentru fiecare caz în parte nu trebuie interpretată ad litteram. De altfel, însăși Comisia de la Veneția a statuat că <em>"nu este neobișnuit ca, urmare a unei condamnări penale pentru o infracțiune gravă, persoanele să fie private de dreptul de a candida în alegeri. Totuși, poate fi considerat problematic dacă dreptul pasiv de a vota este ridicat pe baza oricărei condamnări, indiferent de natura infracțiunii comise. O asemenea interdicție absolută ar putea să nu fie în consonanță cu Convenția Europeană pentru Protecția Drepturilor Omului și Libertăților Fundamentale. (…) Pe de altă parte, ar putea fi nepotrivit să nu fie incluse (sau să nu fie implementate) niciun fel de restricții de eligibilitate pentru infractori."</em></p>
<p>Majoritatea constituțiilor statelor membre ale Consiliului Europei nu conțin prevederi exprese în legătură cu condițiile de eligibilitate ale candidaților la alegerile parlamentare. Unele dintre acestea, precum cele ale Spaniei, Italiei, Irlandei, Elveției, Portugaliei, Slovaciei, Sloveniei, Statului Monaco, Moldovei și Georgiei, statuează că situațiile de ineligibilitate vor fi reglementate prin lege. Cu toate acestea, aproximativ o treime dintre constituțiile avute în vedere de Comisia de la Veneția la elaborarea Raportului Preliminar asupra Excluderii Infractorilor din Parlament conțin diverse prevederi care împiedică persoanele condamnate penal să candideze.</p>
<p>După criteriul motivului ridicării dreptului de a fi ales, există sisteme de drept care prevăd această măsură în funcție de natura infracțiunii (ex. pentru infracțiunile electorale, de corupție, etc.) și sisteme de drept care o prevăd în funcție de natura condamnării (ex. pentru pedeapsa închisorii). După criteriul modului de aplicare a aceleiași măsuri, se disting sisteme de drept în care aceasta rezultă direct din lege, ce stabilește tipul de condamnare și/sau tipul de pedeapsă ori de infracțiune care produce la o atare consecință, respectiv sisteme de drept în care aceasta poate fi dispusă de către instanțele judecătorești, de la caz la caz, ca pedeapsă complementară.</p>
<p>Dintre legile fundamentale europene care limitează într-un fel sau altul dreptul persoanelor condamnate penal să candideze pentru ocuparea unor funcții și demnități publice, menționăm următoarele:</p>
<ul>
<li>Constituția Poloniei - Art. 99 alin. (3): <em>"Nicio persoană condamnată la pedeapsa cu închisoarea printr-o hotărâre judecătorească definitivă pentru o infracțiune săvârșită cu intenție nu poate fi aleasă în Camera Deputaților sau în Senat."</em></li>
<li>Constituția Greciei - Art. 51 alin. (3): <em>"Legea nu poate ridica dreptul la vot, cu excepția situațiilor în care o vârstă minimă nu a fost împlinită, sau în cazul unei incapacități legale, ori ca rezultat al unei condamnări penale irevoca bile pentru anumite infracțiuni."</em></li>
<li>Constituția Danemarcei - Art. 30 alin. (1): <em>"Orice persoană care are dreptul să voteze la alegerile parlamentare trebuie să fie eligibilă pentru a deveni membru al Parlamentului, exceptând situația în care a fost condamnată pentru o faptă care, în opinia publicului, o face nedemnă să fie membru al Parlamentului."</em></li>
<li>Constituția Islandei - Art. 34: <em>"Orice cetățean care are dreptul să voteze la alegerile parlamentare și o reputație neștirbită este eligibil pentru a deveni membru al Parlamentului."</em> Conform art. 5 al Legii nr. 24/2000 privind alegerile parlamentare, nu mai poate fi considerată ca având o reputație neștirbită persoana condamnată de o instanță judecătorească pentru comiterea unei fapte considerate odioasă de opinia, prin această noțiune înțelegându-se orice infracțiune pedepsită de instanța judecătorească cu închisoarea de cel puțin 4 ani cu executare.</li>
<li>Constituția Ucrainei - Art. 76: <em>"Un cetățean care are cazier judiciar pentru săvârșirea unei infracțiuni cu intenție nu poate fi ales în Parlamentul Ucrainei dacă interdicția nu este consumată și ridicată conform procedurii stabilite prin lege."</em></li>
<li>Constituția Luxemburgului - Art. 53: <em>"Nu pot fi alegători și nici eligibili: 1. condamnații la pedepse penale; 2. cei care, într-o cauză corecțională, sunt privați de dreptul la vot prin sentință; 3. majorii aflați sub curatelă. Niciun alt caz de excludere nu poate fi prevăzut. Dreptul la vot poate fi restabilit prin grațierea persoanelor care l-au pierdut prin sentință penală."</em></li>
<li>Constituția Estoniei - Art. 58: <em>"Participarea la vot poate fi restrânsă prin lege pentru cetățenii estonieni care au fost condamnați de o instanță judecătorească și execută sentințe în instituții penale."</em></li>
</ul>
<p>În cadrul unui sistem electoral ideal, mecanismele democratice ar trebui să garanteze că persoanele considerate nedemne să decidă asupra legislației nu ajung decât cel mult în opoziție, iar alegătorii ar trebui să poată împiedica infractorii să ajungă la guvernare. Comisia de la Veneția observă însă că, în realitate, alegerea votanților poate fi alterată, în special dacă aceasta ignoră faptul că un candidat a fost condamnat penal, sau poate fi supusă unor presiuni, mai ales în prezența unor fenomene precum corupția sau crima organizată.</p>
<p>În țările care utilizează scrutinul cu liste închise, printre care se numără și România, este practic imposibil ca alegătorii să lase infractorii pe dinafară, împrejurare care justifică implementarea unor restricții ceva mai severe în privința drepturilor electorale pasive. Comisia de la Veneția susține că în cazurile mai grave este perfect admisibil ca aceste drepturi să fie limitate, inclusiv după eliberarea unui deținut, cu condiția ca măsura respectivă să nu fie aplicată pe întreaga durată a vieții acestuia. Mai mult decât atât, s-a considerat că ridicarea dreptului de a fi ales poate fi dispusă chiar și atunci când o persoană este condamnată la pedeapsa închisorii cu suspendare, sau după ce a fost grațiată.</p>
<p>Având în vedere că aceste probleme sunt legate de restricția unor drepturi fundamentale și de organizarea puterii publice, care sunt domenii constituționale prin excelență, Comisia de la Veneția arată că este justificat să fie reglementate prin prevederi constituționale, ceea ce nu exclude însă posibilitatea reglementării (și) prin legislația ordinară, de preferință cea electorală, nu neapărat cea penală.</p>
<p>În acord cu toate principiile generale și speciale enunțate mai sus, propunem revizuirea Constituției în sensul completării art. 27 cu un nou alineat, alin. (3), prin care cetățenii condamnați definitiv la o pedeapsă privativă de libertate pentru infracțiuni săvârșite cu intenție să nu mai poată fi aleși în organele administrației publice locale, în Camera Deputaților, în Senat și în funcția de Președinte al României, până la intervenirea unei situații care înlătură această consecință extrapenală a condamnării (n.r. reabilitarea, amnistia, dezincriminarea), reglementată prin lege organică.</p>
<p>Considerăm că textul propus respectă în totalitate Declarația Universală a Drepturilor Omului, pactele și tratatele internaționale la care România este parte, jurisprudența Curții Europene a Drepturilor Omului, recomandările Comisiei de la Veneția și concordă cu prevederile similare care se regăsesc în constituțiile unor state europene cu îndelungate tradiții democratice, cel puțin în virtutea următoarelor considerente principale:</p>
<ul>
<li>măsura nu se aplică decât persoanelor condamnate definitiv la o pedeapsă privativă de libertate, fiind exonerate cele care primesc pedepse penale mai ușoare (ex. amenda penală), pentru respectarea principiului proporționalității, potrivit căruia ridicarea dreptului de a fi ales trebuie aplicată numai pentru infracțiunile cu gravitate sporită;</li>
<li>măsura nu se aplică decât condamnaților care au săvârșit fapte penale cu intenție, fiind exonerați cei care au comis infracțiuni din culpă, deoarece acestea prezintă un grad de pericol social mai redus și nu pot fi apreciate ca fiind de natură să pună sub semnul îndoielii onestitatea și moralitatea făptuitorului;</li>
<li>măsura nu privește doar candidaturile pentru Camera Deputaților, Senat și Președinția României, ci și cele pentru organele administrației publice locale, ca o recunoaștere a importanței semnificative a acestor funcții publice și pentru asigurarea egalității de tratament la nivelul întregii administrații, printr-o reglementare unitară și coerentă sub acest aspect;</li>
<li>măsura nu se aplică pentru întreaga durată a vieții condamnaților, fiind în mod expres limitată până la intervenirea unei situații care, potrivit legii organice, înlătură această consecință extrapenală a condamnării; aceste situații sunt în prezent dezincriminarea faptei, amnistia postcondamnatorie și reabilitarea, aceasta din urmă putând fi de drept (care operează în temeiul legii, dacă persoana condamnată la pedeapsa amenzii sau a închisorii de până la 2 ani nu săvârșește o altă infracțiune în decurs de 3 ani de la data executării pedepsei) și judecătorească (care se dispune la cerere, prin hotărâre judecătorească, dacă persoana condamnată la pedeapsa închisorii cuprinse între 2 ani și 25 de ani nu săvârșește o altă infracțiune în decurs de 4 până la 10 ani de la data executării pedepsei).</li>
</ul>
<img src="build/img/lege.png" alt="Lege de revizuire">
<div class="footer"><a href="<?= SITE_URL ?>"><span class="glyphicon glyphicon-menu-left"></span> Înapoi</a></div>
</div>
<div class="col-md-4 comunicate-de-presa">
<h4>Comunicate de presă</h4>
<div class="comunicat row">
  <a href="comunicate-de-motive.php" class="col-md-12" style="background-image: url('build/img/comunicate/conferinta-de-presa.png')"></a>
  <div class="corp col-md-12">
    <span>28 Ianuarie 2018</span>
    <h4><a href="">USR strânge semnături pentru a interzice prin Constituție penalii în funcții publice</a></h3>
    <p>Uniunea Salvați România inițiază strângerea de semnături pentru o inițiativă cetățenească ce transpune...</p>
    <a href="comunicate-de-presa.php">Articolul complet <span class="glyphicon glyphicon-menu-right"></span></a>
  </div>
</div>
</div>
</div>
<?php
require_once 'include/footer-secundar.php';
?>
